add reducers and action
Nezerwa/Bookstore-react-redux pull request #3
Opened 2023-03-08 10:08 UTC by Nezerwa

in this branch i : 
-[] Added Redux Toolkit.
-[] Created a directory that will contain all your Redux logic.
-[] Configured a Redux store (/src/redux/store.js)

2023-03-08 11:10 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️
Hi @Nezerwa, 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you are almost there!  😃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

## Highlights
✅ No Linter error
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)
✅ Neat Commit messages

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 11:10 UTC, bobb-Rob commented on package.json
> +    "redux": "^4.2.1",
- [ ] As stated in the project requirement, you are expected to use Redux Toolkit (npm install react-redux @reduxjs/toolkit) instead of ordinary `redux. **_Please install Redux Toolkit(npm install react-redux @reduxjs/toolkit)._** 🥺 🙏🏾

2023-03-08 11:10 UTC, bobb-Rob commented on src/redux/configureStore.js
> +}
- [ ] If you use Redux/toolkit, you will have available `configureStore` function for use by importing it as show in the code snippet below: Read about  configureStore function [here.](https://redux-toolkit.js.org/api/configureStore).

```Javascript
import { configureStore } from "@reduxjs/toolkit"

export default configureStore({
  reducer: {} //add reducers here
})
``` 
The `configureStore` here replaces the original `createStore` from Redux. Unlike createStore, configureStore from Redux Toolkit not only creates a store but can also accept reducer functions as arguments and automatically sets up the Redux DevTools Extension for easy debugging.


**See project requirement 👇🏾** 
--- | 
![image](https://user-images.githubusercontent.com/84156714/223690525-0d8713a7-1101-4b1c-a7f6-f1c8ee7b8951.png)

2023-03-08 11:10 UTC, bobb-Rob commented on src/redux/books/books.js
> +};
- [ ] For this BookSlice, you are expected to use `createSlice` from the redux toolkit. Learn more about this function [here ](https://medium.com/geekculture/understanding-createslice-in-redux-toolkit-reactjs-eca8d20f45d7) and [here](https://redux-toolkit.js.org/api/createSlice). 

This means you will not have to create your actions separately as the createSlice function will generate them automatically for you. 

Please use this createSlice function also in the categoriesSlice

2023-03-09 11:16 UTC, DuaneDave requested changes
Hi @Nezerwa 👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ Meaningful commit history
✔️ PR summary present
✔️ Good usage of createSlice

 ## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-09 11:16 UTC, DuaneDave commented on src/redux/categories/categories.js
> +};
As previously mentioned, you are supposed to refactor the logic here to use `createSlice` just as you have done with the books.js. Please do this to keep up with the modern approach and to stick with the milestone's requirement.

2023-03-09 13:43 UTC, BregornOriginal approved these changes
## Hi @Nezerwa 

## Your project is complete!  There is nothing else to say other than... it's time to merge it 

## Congratulations! 

![giphy (1)](https://user-images.githubusercontent.com/93630700/224042773-ef7bb886-f512-4508-a4a2-043982827c52.gif)

## Highlights

✅ Linters are passing
✅ Good work implementing changes requested by the previous reviewer

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

2023-03-11 20:31 UTC, merged